### ISSUE TITLE
Gradle targets for DevelopmentRun

### ISSUE THREAD

**Issue by clojj** [noobymatze/knack#2]
Hi @noobymatze 

since I am not very familiar with the KotlinJS ecosystem, I wonder if the various gradle-targets "browserDevelopmentRun" etc. should enable Hot-reloading after some change + build in the code (knack-example) ?

https://kotlinlang.org/docs/dev-server-continuous-compilation.html

adding --continuous givs me:

`Unknown command-line option '--continuous'.`

**Comment by noobymatze** [comment]
Hi @clojj I am neither. :-D It's the first multi-module project with gradle, I ever did.

Hm, for me running either of the following commands seems to work, if you cd into 'knack-example', albeit super slowly...

```sh
$ ../gradlew browserDevelopmentRun --continuous
$ ../gradlew run --continuous
```

I am not sure, if it works, if you are in the parent directory.

EDIT: Does that help?

**Comment by clojj** [comment]
yep, works, so it's some IntelliJ issue because I ran it in the Gradel tool window initially
